language: rust
matrix:
  include:
    - rust: "nightly"
      env: TEST_SUITE=suite_nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "$TEST_SUITE" = "suite_nightly" ]; then
      cargo bench --verbose;
    fi
